[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.0.0-dev.38", features = ["log"] }
anyhow = "1"
log = "0.4"
parking_lot = "0.12.1"
simplelog = "0.12.1"
lazy_static = "1.4.0"
serde_json = "1"
zytex_wallet = { git = "https://gitlab.com/zytex/zytex-blockchain", branch = "main", package = "zytex_wallet", features = ["api_server"] }
zytex_common = { git = "https://gitlab.com/zytex/zytex-blockchain", branch = "main", package = "zytex_common" }
serde = { version = "1.0.197", features = ["derive"] }
